name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: actions/checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
        with:
        node-version: '18'
      - name: Run all cypress tests
        run: npx cypress run

