name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18" # Use a stable Node.js version compatible with Cypress

      - name: Install dependencies
        run: npm install

      - name: Run all Cypress tests
        run: npx cypress run
